### ISSUE TITLE
Connect calendars

### ISSUE THREAD

**Issue by AnandBaburajan** [AnandBaburajan/Kukkee#104]
It would be helpful for the poll creator if we could show them which slots are already occupied (via their Google calendar). I'm not sure if we can modify `react-available-times` for this purpose. Might need to embed a calendar otherwise. Are there more solutions? Let us know!

**Comment by mdPial** [comment]
I would like to work on that issue. Is it okay to use other npm packages?.  I want to use this one https://www.npmjs.com/package/@ericz1803/react-google-calendar

**Comment by AnandBaburajan** [comment]
@mdPial Thanks :D yep, we can use other packages after discussing the idea you've in mind. Also since you're interested to look into the Google Calendar parts, I would like to know if you would like to work on https://github.com/RocketMeet/RocketMeet-client/issues/103 - which is much more important for us. What do you think?

**Comment by mdPial** [comment]
I have looked into that issue. I can work on it.
For this issue If we just show all the events serially by date, I think we can do it by using the official calendar API.
![image](https://user-images.githubusercontent.com/43095489/112363058-4cebc100-8cff-11eb-937e-5c99bd056c2b.png)

I wanted to show a calendar like this as you said to embed the calendar. In this calendar, they get lots of interactive options to do. But I have not found anything for inviting peoples by using code of `react-google-calendar` package though using `fullcalendar` we might achieve this.
![image](https://user-images.githubusercontent.com/43095489/112362616-d3ec6980-8cfe-11eb-89f6-086fcc482bfd.png)

**Comment by AnandBaburajan** [comment]
Showing another calendar on the page would be too much so maybe we can 'just show all the events serially by date' and time.

**Comment by mdPial** [comment]
Okay. I Will start first with #103

**Comment by mdPial** [comment]
As other person is still working with #103. Should I start now?

**Comment by AnandBaburajan** [comment]
> Should I start working in this #104 issue now?

:+1:

**Comment by mdPial** [comment]
Will everyone will follow only one calendar?

**Comment by AnandBaburajan** [comment]
> Will everyone follow only one calendar?

I don't know much about Google Calendar but I think we can get events from the default personal calendar?

**Comment by mdPial** [comment]
Yes we can.

**Comment by mdPial** [comment]
Sorry for taking a long time. Many things came at once day after day( assignment+exam+hackathon ) :sweat:   . I will start working fully from tomorrow.

**Comment by AnandBaburajan** [comment]
> Sorry for taking a long time. Many things came at once day after day( assignment+exam+hackathon ) :sweat:   . I will start working fully from tomorrow.

Hakuna matata! Is the hackathon part of Local Hack Day? Just a guess :D Thanks for joining us again.

**Comment by mdPial** [comment]
> Hakuna matata

😆 thought japanese language.

> Is the hackathon part of Local Hack Day?

Not actually. I participated in another hackathon. But I am participating in Local Hack Day also. But it's not pressuring me 😃. I am solving only easy ones 😂  to save time.

>Thanks for joining us again.

 😁

**Comment by AnandBaburajan** [comment]
Updates: `react-available-times`'s API seems to let users show their calendars on top of the time slots. Also, renaming this issue to support more calendars than just Google's.

**Comment by AnandBaburajan** [comment]
An updated explanation for this feature: end switching tabs between Kukkee and personal/work calendars while selecting times by connecting Google, Outlook, etc., calendars.

**Comment by PeerRich** [comment]
talking from experience, connecting various calendars is a pain. we hope to make it easier and hope to release a proper library for that. not sure what your timeline here is

**Comment by AnandBaburajan** [comment]
@PeerRich sounds interesting! We aim to at least integrate some popular calendars (after talking to our potential users) asap. Looking forward to checking out what you all build over there and maybe contributing there too.

**Comment by AnandBaburajan** [comment]
Closing since we want to keep Kukkee as simple as possible, and there's no plan for calendar integrations now.
