### ISSUE TITLE
Integrate calendar into poll voting page

### ISSUE THREAD

**Issue by AnandBaburajan** [AnandBaburajan/Kukkee#105]
It would be helpful for the voter if we could show them which slots are already occupied (via their calendar).

**Comment by AnshMishra2001** [comment]
Can I start working on this issue, till we arrive at a conclusion regarding the discussion issue ?

**Comment by AnandBaburajan** [comment]
Sure, thanks! Let us know your ideas and queries at our chatroom!

**Comment by AnandBaburajan** [comment]
@AnshMishra2001 if you're still interested, pls let us know and also share what you plan to do, thanks!

**Comment by AnandBaburajan** [comment]
Update: this is an interesting feature, although we're not sure if there are users interested in this.

**Comment by AnandBaburajan** [comment]
Closing since we want to keep Kukkee as simple as possible, and there's no plan for calendar integrations now.
