### ISSUE TITLE
'Set deadline for poll' option

### ISSUE THREAD

**Issue by AnandBaburajan** [AnandBaburajan/Kukkee#123]
Set a deadline to receive votes in time. After the deadline, no more votes are allowed.

**Comment by nishihere19** [comment]
I would like to work on this feature. Kindly assign it to me.

**Comment by AnandBaburajan** [comment]
Hey @nishihere19! Thanks for showing interest!

**Comment by AnandBaburajan** [comment]
Closing since we want to keep Kukkee as simple as possible.
