### ISSUE TITLE
Video conferencing integrations

### ISSUE THREAD

**Issue by AnandBaburajan** [AnandBaburajan/Kukkee#172]
Automatically add [Jitsi Meet](https://github.com/jitsi/jitsi-meet), Zoom, Google Meet, Microsoft Teams, etc. meeting links when a user finalises the meeting time.

**Comment by wolftune** [comment]
Please prioritize Free/Libre/Open tools, not just include but put them *first* and label them as being FLO so that people can see the distinction between those and proprietary options. meet.jit.si being the dominant one to suggest at this time.

**Comment by AnandBaburajan** [comment]
Good point, thanks!

**Comment by AnandBaburajan** [comment]
Closing since we want to keep Kukkee as simple as possible.
