### ISSUE TITLE
Doodle has options for booking available time slots with people can this have that? 

### ISSUE THREAD

**Issue by Leopere** [AnandBaburajan/Kukkee#192]
Bonus if there could maybe eventually be payment processor integration as well at some point.

**Comment by AnandBaburajan** [comment]
Hello @Leopere. We're primarily focusing on "group polls". For booking pages, you can check out [Cal](https://github.com/calcom/cal.com).

CC @PeerRich.

**Comment by PeerRich** [comment]
hey hey thank you for tagging. We can help with Stripe. @AnandBaburajan also cool project you started here. wanna jump on a call? cal.com/peer

**Comment by AnandBaburajan** [comment]
@PeerRich thanks, yep! Happy to connect with you!
