### ISSUE TITLE
Time-slot component on create-poll not working as expected on mobile

### ISSUE THREAD

**Issue by AnandBaburajan** [AnandBaburajan/Kukkee#37]
The react-available-times component has some isses on mobile like not being able to adjust the interval or move the slots around. This would require some PRs at the react-available-times' upstream. It's quite old and throws some deprecation warnings too.

**Comment by VishnuSanal** [comment]
It would be great if the time slot component scrolls to the current time :)

**Comment by anaswaratrajan** [comment]
@AnandBaburajan @VipinVIP @BreadGenie What do you guys think of building a custom time-slot UI from scratch? Or utilise libraries like moment.js or moment-timezone.js to implement a custom UI? I feel like r-a-t could be a dead-end for us if need for more features in the future.

**Comment by AnandBaburajan** [comment]
@anaswaratrajan that would require building a component similar to r-a-t plus more features from scratch. So what do you think about contributing to r-a-t and enhancing it instead?

**Comment by BreadGenie** [comment]
> @anaswaratrajan that would require building a component similar to r-a-t plus more features from scratch. So what do you think about contributing to r-a-t and enhancing it instead?

imo this is better unless the time slot component's evolution is supposed to be different from r-a-t 
I'll start working on it after exams (add type and other stuff)

**Comment by BreadGenie** [comment]
I was wondering on how to implement adjusting the interval and moving the slots. One idea that came to my mind would be to use press and hold (long press) and then drag either for adjusting the interval or for moving the slots.
Any other ideas?

**Comment by AnandBaburajan** [comment]
> I was wondering on how to implement adjusting the interval and moving the slots for mobile devices. One idea that came to my mind would be to use press and hold (long press) and then drag either for adjusting the interval or for moving the slots.

Thanks! Yep, this could work.

**Comment by AnandBaburajan** [comment]
Updates: on mobile, only 1 hour slots can be created due to limitations in react-available-times. We would contribute to react-available-times but I think we should wait for some time to see how many users would want this to be fixed.

If you want to be able to select more than 1 hour slots on mobile, please let us know!

**Comment by AnandBaburajan** [comment]
Let's checkout https://github.com/jquense/react-big-calendar too

**Comment by AnandBaburajan** [comment]
> Let's checkout https://github.com/jquense/react-big-calendar too

Kukkee's using this now, so closing this issue.
